language: cpp

os:
  - linux
  - osx

dist: bionic
sudo: required

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  - CONFIG=Release TESTS_CXX_STD=17
  #- CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - g++ --version
  - 'if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew upgrade cmake; 
    else 
      wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null &&
      sudo apt-add-repository -y "deb https://apt.kitware.com/ubuntu/ bionic main" &&
      sudo apt-get update -qq -y &&
      sudo apt-get install -y cmake &&
      sudo rm -r /usr/local/cmake-3.12.4/;
    fi'

before_script:
   - mkdir build
   - cd build
   - if [[ "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then
         cp -r ../scripts/ . &&
         cp -r ../test_scripts/ . &&
         sudo apt-get install python-pyparsing;
     fi
   - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXXFLAGS="--coverage"; fi
   - if [[ -n "${TESTS_CXX_STD:-}" && "$TRAVIS_OS_NAME" = "osx" ]]; then ADD_OPTS="-DSQLPP11_TESTS_CXX_STD=$TESTS_CXX_STD"; fi
   - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=$PWD/../date $ADD_OPTS

script:
   - cmake --build . --config $CONFIG
   - ctest --output-on-failure

after_script:
  - ../coveralls
